[book]
title = "Bioinformatics Handbook"
authors = ["PreSeqDataLab"]
language = "zh"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/PreSeqDataLab/bioinformatics"
edit-url-template = "https://github.com/PreSeqDataLab/bioinformatics/edit/main/{path}"
additional-css = ["src/style.css"]
additional-js = ["src/submenu.js"]
